import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {loadGlobal, loadArticle, loadArticles} from "../../../lib/strapi";

const Article = ({ menu, meta, article, error }) => {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {article.title}
                </h1>

                MENU:
                <ul>
                    <li><Link href="/">Home</Link></li>
                    {menu.map(function(m, idx){
                        return (<li key={idx}><Link href={m.href}>{m.title}</Link></li>)
                    })}
                </ul>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>
        </div>
    )
}

/*Home.getInitialProps = async ctx => {
  return loadGlobal()
};*/

export const  getStaticProps = async (props) => {
    //console.log('STATIC PROPS:', props)
    const { menu, meta } = await loadGlobal()
    const { article } = await loadArticle(props.params.slug)
    return { props: { menu, meta, article }, revalidate: 10 }
}

// instructs next to render all user profiles using SSG
export const getStaticPaths = async () => {
    const {articles} = await loadArticles()
    const paths = articles.map(article => `/news/${article.id}`);
    return { paths, fallback: false };
}

export default Article;